jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod?currentSchema=bakery
    username: bakery_prod
    password: ENC(1B95tKSYxomlH8SeQDgZY1BwrLpHMfj1)

  mustache:
    expose-request-attributes: true

  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: ENC(6PB+nFOG8Bgz+GWNlvi1BZggVTAuabEa)
            client-secret: ENC(TV/eXgCu3h0KCTsluF8QgzvPcwMx3328asz+KrzlwB6tgReKCRJfm5x4d8/QejGu)
            scope:
              - email
              - public_profile
            user-name-attribute: email

logging:
  level:
    root: INFO

paypal:
  client-id: ENC(DW1kmSrHL7fjZ4ZvKUG/TSdJOeogzNMoZwHqnJN7b8m5GFeEvGqxbJcfuZwffUoXt2GB7gGUHmsFFVZJHpVhyu3X1nwsME7KfbsiD6VYJbBKtmRRuj+ogevx2yEZCSJ3)
  client-secret: ENC(cIfLsJ1/aRtsDGPuOGrGqgKLWhnobwL81PZauVUNLLL1DRe7+S9/5K3ZLuuRrpVjFcxKA1Wn7Oblym3p5nCjmWxtHDA4JJX304gK7Bclg6O9Mrby2Unfvdl9YW5cQ1A6)
  brand-name: N-2 Bakery
  currency-code: GBP
  country-code: GB
  return-url: http://localhost:8080/checkout/complete
  cancel-url: http://localhost:8080/checkout/cancel
  landing-page: LOGIN
  shipping-preference: SET_PROVIDED_ADDRESS
  user-action: PAY_NOW

message:
  badCredentials: We didn't recognise your details. Please check your email and password.
  loginFailed: Login failed. Please try again.
  emailInUse: Email address already in use. Please provide another one.
  invalidEmail: Invalid email address.
  invalidPassword: Password must be between 6 and 8 characters.
  invalidAddressLine1: Invalid address line 1.
  invalidPostcode: Invalid postcode.
  accountUpdated: Account details updated.
