jasypt:
  encryptor:
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    algorithm: PBEWithMD5AndDES

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prod?currentSchema=bakery
    username: bakery_prod
    password: ENC(1B95tKSYxomlH8SeQDgZY1BwrLpHMfj1)

  mustache:
    expose-request-attributes: true