spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/prod?currentSchema=bakery
    username: bakery_prod
    password: ENC(1B95tKSYxomlH8SeQDgZY1BwrLpHMfj1)

  flyway:
    schemas: bakery
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:com/natay/ecomm/bakery/user/db/migration
      - classpath:com/natay/ecomm/bakery/product/db/migration